### ISSUE TITLE
连对 顺子 等多牌经常报错重置

### ISSUE THREAD

**Issue by dysf888** [Vincentzyx/DouZero_For_HLDDZ_FullAuto#5]
下家 出牌 KKQQJJTT
运行时出现错误，已重置
 ValueError("Coordinate 'lower' is less than 'upper'")
Traceback (most recent call last):
  File "D:\Study\DouZero_For_HLDDZ_FullAuto\main.py", line 269, in init_cards
    self.start()
  File "D:\Study\DouZero_For_HLDDZ_FullAuto\main.py", line 525, in start
    self.handle_others(self.RPlayedCardsPos, self.RPlayedCard, "下家")
  File "D:\Study\DouZero_For_HLDDZ_FullAuto\main.py", line 391, in handle_others
    self.waitUntilNoAnimation()
  File "D:\Study\DouZero_For_HLDDZ_FullAuto\main.py", line 281, in waitUntilNoAnimation
    ani = self.haveAnimation(ms)
  File "D:\Study\DouZero_For_HLDDZ_FullAuto\main.py", line 759, in haveAnimation
    if not self.compareImage(img.crop(region), lastImg.crop(region)):
  File "D:\Programe\py310\lib\site-packages\PIL\Image.py", line 1206, in crop
    raise ValueError("Coordinate 'lower' is less than 'upper'")
ValueError: Coordinate 'lower' is less than 'upper'

**Comment by maxiaowei0216** [comment]
应该是作者把`haveAnimation`里的regions列表中的某个区域参数设置错了，把`(478, 433, 852, 63)`这行注释掉就行，但是可能会影响部分动画的判断。

**Comment by Vincentzyx** [comment]
> 应该是作者把`haveAnimation`里的regions列表中的某个区域参数设置错了，把`(478, 433, 852, 63)`这行注释掉就行，但是可能会影响部分动画的判断。

谢谢，我修复一下
